<a href="https://colab.research.google.com/github/Farheen-Qazi/Data_Science_And_Structures/blob/main/20SW055(LAB_4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***LAB 4 TASKS***

Task Number *One*

In [2]:
import numpy as np


X = np.arange(1, 26).reshape(5, 5)


Y = X[X % 2 != 0]

print("Original array:\n", X)
print("Array with odd numbers:\n", Y)

Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Array with odd numbers:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


Task Number *Two*

In [1]:
import numpy as np


even_numbers = np.arange(2, 33, 2)


X = even_numbers.reshape(4, 4)

print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


Task Number *Three*

In [3]:
import numpy as np


X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


Task Number *Four*

In [5]:
from google.colab import drive
drive.mount('/NumPy.ipnyb')

import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)


# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)

Mounted at /NumPy.ipnyb
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[ 1.43360152 -1.47314555  1.61927254 ... -0.71594041 -0.92303485
   0.72394821]
 [-0.40768825 -1.24622891 -0.76681281 ... -0.32459779 -1.40268354
   0.001692  ]
 [-0.4617633   1.2498541   0.6651178  ... -0.26184802  0.59756816
   1.18686145]
 ...
 [ 0.72994134 -0.01909665  0.32913798 ... -0.22878632  1.45119187
  -1.22879275]
 [-1.5494248   1.45003433  0.18664342 ...  0.45876218  0.83567703
  -0.11333915]
 [ 1.2056649   1.49665165 -1.32421799 ...  1.13416557 -0.00833999
   1.59888212]]
Average of all values in X_norm: 1.6342482922482304e-17
Average of minimum values in each column of X_norm: -1.7264394336800888
Average of maximum values in each column of X_norm: 1.727799678857322
Random permutation of row indices: [262 203 113 975 394 859 464 347 738 312 577 749 672 618 482 679 458 332
 490 314 448 706 116  98 268 120 338  30  28 204 304 170 719 895 836 687
 807 628 173  64 217 285 